### ISSUE TITLE
Criar métodos da classe Object

### ISSUE THREAD

**Issue by juanbelieni** [juanbelieni/fgv-jogo-de-nave#1]
Implementar os seguintes métodos na classe Object, localizado em `src/objects/object.py`:

- [x] `collides_with(self, other)`: retorna se o objeto está colidindo com o outro ou não.
- [x] `move(self, delta)`: move o objeto com base no delta, que é um vetor.

Obs.: a posição, o tamanho e o delta da posição do objeto são vetores 2D do pygame.

**Comment by phf-souza** [comment]
Eu faço essa
