### ISSUE TITLE
Separar os sprites das naves

### ISSUE THREAD

**Issue by juanbelieni** [juanbelieni/fgv-jogo-de-nave#2]
Os sprites das naves estão no arquivo `src/sprites/ship/ships.png`, e estão todos juntos em uma imagem só.

![Naves](https://user-images.githubusercontent.com/29464328/120908650-b3b42180-c642-11eb-9b27-a2cd7579979e.png)

As opções para realizar essa tarefa são:

- Usar o pygame para separar via código os sprites.
- Separar na mão, cortando os sprites e exportando cada um em novas imagens com o padrão `red_ship_1.png`. Obs.: é importante que todos os sprites tenham o mesmo tamanho.

**Comment by nicolessouza** [comment]
Vou fazer essa
