### ISSUE TITLE
Criar classe do tiro

### ISSUE THREAD

**Issue by juanbelieni** [juanbelieni/fgv-jogo-de-nave#7]
Essa classe deverá ser criada em `src/objects/shoot.py`, conforme o seguinte:

- [x] Deverá estender a classe `Object`
- [x] A velocidade do tiro deve ser passado no construtor, e guardada em uma propriedade dentro da classe
- [x] A cada passo (`step`), o tiro vai se mover no eixo _x_ indo da esquerda para a direita na velocidade especificada

**Comment by CarlSouza** [comment]
eu vou tentar pegar essa
